services:
    phpbbmodders.banhammer.listener:
        class: phpbbmodders\banhammer\event\banhammer_listener
        arguments:
            - '@auth'
            - '@cache.driver'
            - '@config'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '@phpbbmodders.banhammer.core.bantime'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '%core.table_prefix%banhammer_restrict'
        tags:
            - { name: event.listener }
    phpbbmodders.banhammer.admin.controller:
        class: phpbbmodders\banhammer\controller\admin_controller
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '@log'
            - '@phpbbmodders.banhammer.core.bantime'
    phpbbmodders.banhammer.core.bantime:
        class:  phpbbmodders\banhammer\core\bantime
        arguments:
            - '@user'
    phpbbmodders.banhammer.controller.ban_domain:
        class: phpbbmodders\banhammer\controller\ban_domain_controller
        arguments:
            - '@auth'
            - '@language'
            - '@request'
            - '@user'
    phpbbmodders.banhammer.cron.restriction_expiry:
        class: phpbbmodders\banhammer\cron\task\restriction_expiry
        arguments:
            - '@config'
            - '@dbal.conn'
            - '%core.table_prefix%banhammer_restrict'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: cron.task }
